name: ubuntu

on: [push, pull_request, workflow_dispatch]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC9
        shell: bash
        run:  |
          sudo apt update
          sudo apt install gcc-9 g++-9
          sudo apt install libgl1-mesa-dev

      - name: Install Xvfb
        shell: bash
        run: |
          sudo apt install xvfb

      - name: Start Xvfb
        shell: bash
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Set Display Environment Variable
        shell: bash
        run: |
          export DISPLAY=:99

      - name: Get Conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.60.0

      - name: Add Bincrafters Remote
        run: conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UNIT_TESTS=ON
        env:
          CC:  gcc-9
          CXX: g++-9

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Tests
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: xvfb-run ctest --rerun-failed --output-on-failure
