name: ubuntu

on:
  push:
    branches:
      - master
    paths:
      - CMakeLists.txt
      - include/**
      - src/**
      - tests/**
  pull_request:
    paths:
      - CMakeLists.txt
      - include/**
      - src/**
      - tests/**

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC9
        shell: bash
        run:  |
          sudo apt update
          sudo apt install gcc-9 g++-9
          sudo apt install libgl1-mesa-dev

      - name: Get Conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.60.0

      - name: Add Bincrafters Remote
        run: conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install Required Packages
        run: |
          sudo apt update
          sudo apt install -y libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UNIT_TESTS=ON
        env:
          CC:   gcc-9
          CXX:  g++-9

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Tests
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest --rerun-failed --output-on-failure
